// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateAccountEvent.proto

package javaprotobuf;

public final class UpdateAccountEventOuterClass {
  private UpdateAccountEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateAccountEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:javaprotobuf.UpdateAccountEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The slot number when this update was emitted.
     * </pre>
     *
     * <code>uint64 slot = 1;</code>
     * @return The slot.
     */
    long getSlot();

    /**
     * <pre>
     * The Pubkey for the account.
     * </pre>
     *
     * <code>bytes pubkey = 2;</code>
     * @return The pubkey.
     */
    com.google.protobuf.ByteString getPubkey();

    /**
     * <pre>
     * The lamports held by the account.
     * </pre>
     *
     * <code>uint64 lamports = 3;</code>
     * @return The lamports.
     */
    long getLamports();

    /**
     * <pre>
     * The Pubkey of the owner program account.
     * </pre>
     *
     * <code>bytes owner = 4;</code>
     * @return The owner.
     */
    com.google.protobuf.ByteString getOwner();

    /**
     * <pre>
     * This account's data contains a loaded program.
     * </pre>
     *
     * <code>bool executable = 5;</code>
     * @return The executable.
     */
    boolean getExecutable();

    /**
     * <pre>
     * The epoch at which this account will next owe rent.
     * </pre>
     *
     * <code>uint64 rent_epoch = 6;</code>
     * @return The rentEpoch.
     */
    long getRentEpoch();

    /**
     * <pre>
     * The data held in this account.
     * </pre>
     *
     * <code>bytes data = 7;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <pre>
     * A global monotonically increasing atomic number, which can be used
     * to tell the order of the account update. For example, when an
     * account is updated in the same slot multiple times, the update
     * with higher write_version should supersede the one with lower
     * write_version.
     * </pre>
     *
     * <code>uint64 write_version = 8;</code>
     * @return The writeVersion.
     */
    long getWriteVersion();
  }
  /**
   * Protobuf type {@code javaprotobuf.UpdateAccountEvent}
   */
  public static final class UpdateAccountEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:javaprotobuf.UpdateAccountEvent)
      UpdateAccountEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateAccountEvent.newBuilder() to construct.
    private UpdateAccountEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateAccountEvent() {
      pubkey_ = com.google.protobuf.ByteString.EMPTY;
      owner_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UpdateAccountEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateAccountEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              slot_ = input.readUInt64();
              break;
            }
            case 18: {

              pubkey_ = input.readBytes();
              break;
            }
            case 24: {

              lamports_ = input.readUInt64();
              break;
            }
            case 34: {

              owner_ = input.readBytes();
              break;
            }
            case 40: {

              executable_ = input.readBool();
              break;
            }
            case 48: {

              rentEpoch_ = input.readUInt64();
              break;
            }
            case 58: {

              data_ = input.readBytes();
              break;
            }
            case 64: {

              writeVersion_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return javaprotobuf.UpdateAccountEventOuterClass.internal_static_javaprotobuf_UpdateAccountEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return javaprotobuf.UpdateAccountEventOuterClass.internal_static_javaprotobuf_UpdateAccountEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent.class, javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent.Builder.class);
    }

    public static final int SLOT_FIELD_NUMBER = 1;
    private long slot_;
    /**
     * <pre>
     * The slot number when this update was emitted.
     * </pre>
     *
     * <code>uint64 slot = 1;</code>
     * @return The slot.
     */
    @java.lang.Override
    public long getSlot() {
      return slot_;
    }

    public static final int PUBKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString pubkey_;
    /**
     * <pre>
     * The Pubkey for the account.
     * </pre>
     *
     * <code>bytes pubkey = 2;</code>
     * @return The pubkey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPubkey() {
      return pubkey_;
    }

    public static final int LAMPORTS_FIELD_NUMBER = 3;
    private long lamports_;
    /**
     * <pre>
     * The lamports held by the account.
     * </pre>
     *
     * <code>uint64 lamports = 3;</code>
     * @return The lamports.
     */
    @java.lang.Override
    public long getLamports() {
      return lamports_;
    }

    public static final int OWNER_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString owner_;
    /**
     * <pre>
     * The Pubkey of the owner program account.
     * </pre>
     *
     * <code>bytes owner = 4;</code>
     * @return The owner.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getOwner() {
      return owner_;
    }

    public static final int EXECUTABLE_FIELD_NUMBER = 5;
    private boolean executable_;
    /**
     * <pre>
     * This account's data contains a loaded program.
     * </pre>
     *
     * <code>bool executable = 5;</code>
     * @return The executable.
     */
    @java.lang.Override
    public boolean getExecutable() {
      return executable_;
    }

    public static final int RENT_EPOCH_FIELD_NUMBER = 6;
    private long rentEpoch_;
    /**
     * <pre>
     * The epoch at which this account will next owe rent.
     * </pre>
     *
     * <code>uint64 rent_epoch = 6;</code>
     * @return The rentEpoch.
     */
    @java.lang.Override
    public long getRentEpoch() {
      return rentEpoch_;
    }

    public static final int DATA_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * The data held in this account.
     * </pre>
     *
     * <code>bytes data = 7;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int WRITE_VERSION_FIELD_NUMBER = 8;
    private long writeVersion_;
    /**
     * <pre>
     * A global monotonically increasing atomic number, which can be used
     * to tell the order of the account update. For example, when an
     * account is updated in the same slot multiple times, the update
     * with higher write_version should supersede the one with lower
     * write_version.
     * </pre>
     *
     * <code>uint64 write_version = 8;</code>
     * @return The writeVersion.
     */
    @java.lang.Override
    public long getWriteVersion() {
      return writeVersion_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (slot_ != 0L) {
        output.writeUInt64(1, slot_);
      }
      if (!pubkey_.isEmpty()) {
        output.writeBytes(2, pubkey_);
      }
      if (lamports_ != 0L) {
        output.writeUInt64(3, lamports_);
      }
      if (!owner_.isEmpty()) {
        output.writeBytes(4, owner_);
      }
      if (executable_ != false) {
        output.writeBool(5, executable_);
      }
      if (rentEpoch_ != 0L) {
        output.writeUInt64(6, rentEpoch_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(7, data_);
      }
      if (writeVersion_ != 0L) {
        output.writeUInt64(8, writeVersion_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (slot_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, slot_);
      }
      if (!pubkey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, pubkey_);
      }
      if (lamports_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, lamports_);
      }
      if (!owner_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, owner_);
      }
      if (executable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, executable_);
      }
      if (rentEpoch_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, rentEpoch_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, data_);
      }
      if (writeVersion_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, writeVersion_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent)) {
        return super.equals(obj);
      }
      javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent other = (javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent) obj;

      if (getSlot()
          != other.getSlot()) return false;
      if (!getPubkey()
          .equals(other.getPubkey())) return false;
      if (getLamports()
          != other.getLamports()) return false;
      if (!getOwner()
          .equals(other.getOwner())) return false;
      if (getExecutable()
          != other.getExecutable()) return false;
      if (getRentEpoch()
          != other.getRentEpoch()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getWriteVersion()
          != other.getWriteVersion()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SLOT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSlot());
      hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPubkey().hashCode();
      hash = (37 * hash) + LAMPORTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLamports());
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
      hash = (37 * hash) + EXECUTABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getExecutable());
      hash = (37 * hash) + RENT_EPOCH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRentEpoch());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + WRITE_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getWriteVersion());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code javaprotobuf.UpdateAccountEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:javaprotobuf.UpdateAccountEvent)
        javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return javaprotobuf.UpdateAccountEventOuterClass.internal_static_javaprotobuf_UpdateAccountEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return javaprotobuf.UpdateAccountEventOuterClass.internal_static_javaprotobuf_UpdateAccountEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent.class, javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent.Builder.class);
      }

      // Construct using javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        slot_ = 0L;

        pubkey_ = com.google.protobuf.ByteString.EMPTY;

        lamports_ = 0L;

        owner_ = com.google.protobuf.ByteString.EMPTY;

        executable_ = false;

        rentEpoch_ = 0L;

        data_ = com.google.protobuf.ByteString.EMPTY;

        writeVersion_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return javaprotobuf.UpdateAccountEventOuterClass.internal_static_javaprotobuf_UpdateAccountEvent_descriptor;
      }

      @java.lang.Override
      public javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent getDefaultInstanceForType() {
        return javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent.getDefaultInstance();
      }

      @java.lang.Override
      public javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent build() {
        javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent buildPartial() {
        javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent result = new javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent(this);
        result.slot_ = slot_;
        result.pubkey_ = pubkey_;
        result.lamports_ = lamports_;
        result.owner_ = owner_;
        result.executable_ = executable_;
        result.rentEpoch_ = rentEpoch_;
        result.data_ = data_;
        result.writeVersion_ = writeVersion_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent) {
          return mergeFrom((javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent other) {
        if (other == javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent.getDefaultInstance()) return this;
        if (other.getSlot() != 0L) {
          setSlot(other.getSlot());
        }
        if (other.getPubkey() != com.google.protobuf.ByteString.EMPTY) {
          setPubkey(other.getPubkey());
        }
        if (other.getLamports() != 0L) {
          setLamports(other.getLamports());
        }
        if (other.getOwner() != com.google.protobuf.ByteString.EMPTY) {
          setOwner(other.getOwner());
        }
        if (other.getExecutable() != false) {
          setExecutable(other.getExecutable());
        }
        if (other.getRentEpoch() != 0L) {
          setRentEpoch(other.getRentEpoch());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getWriteVersion() != 0L) {
          setWriteVersion(other.getWriteVersion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long slot_ ;
      /**
       * <pre>
       * The slot number when this update was emitted.
       * </pre>
       *
       * <code>uint64 slot = 1;</code>
       * @return The slot.
       */
      @java.lang.Override
      public long getSlot() {
        return slot_;
      }
      /**
       * <pre>
       * The slot number when this update was emitted.
       * </pre>
       *
       * <code>uint64 slot = 1;</code>
       * @param value The slot to set.
       * @return This builder for chaining.
       */
      public Builder setSlot(long value) {
        
        slot_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The slot number when this update was emitted.
       * </pre>
       *
       * <code>uint64 slot = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSlot() {
        
        slot_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pubkey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The Pubkey for the account.
       * </pre>
       *
       * <code>bytes pubkey = 2;</code>
       * @return The pubkey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPubkey() {
        return pubkey_;
      }
      /**
       * <pre>
       * The Pubkey for the account.
       * </pre>
       *
       * <code>bytes pubkey = 2;</code>
       * @param value The pubkey to set.
       * @return This builder for chaining.
       */
      public Builder setPubkey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The Pubkey for the account.
       * </pre>
       *
       * <code>bytes pubkey = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPubkey() {
        
        pubkey_ = getDefaultInstance().getPubkey();
        onChanged();
        return this;
      }

      private long lamports_ ;
      /**
       * <pre>
       * The lamports held by the account.
       * </pre>
       *
       * <code>uint64 lamports = 3;</code>
       * @return The lamports.
       */
      @java.lang.Override
      public long getLamports() {
        return lamports_;
      }
      /**
       * <pre>
       * The lamports held by the account.
       * </pre>
       *
       * <code>uint64 lamports = 3;</code>
       * @param value The lamports to set.
       * @return This builder for chaining.
       */
      public Builder setLamports(long value) {
        
        lamports_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The lamports held by the account.
       * </pre>
       *
       * <code>uint64 lamports = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLamports() {
        
        lamports_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString owner_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The Pubkey of the owner program account.
       * </pre>
       *
       * <code>bytes owner = 4;</code>
       * @return The owner.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getOwner() {
        return owner_;
      }
      /**
       * <pre>
       * The Pubkey of the owner program account.
       * </pre>
       *
       * <code>bytes owner = 4;</code>
       * @param value The owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwner(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The Pubkey of the owner program account.
       * </pre>
       *
       * <code>bytes owner = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwner() {
        
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }

      private boolean executable_ ;
      /**
       * <pre>
       * This account's data contains a loaded program.
       * </pre>
       *
       * <code>bool executable = 5;</code>
       * @return The executable.
       */
      @java.lang.Override
      public boolean getExecutable() {
        return executable_;
      }
      /**
       * <pre>
       * This account's data contains a loaded program.
       * </pre>
       *
       * <code>bool executable = 5;</code>
       * @param value The executable to set.
       * @return This builder for chaining.
       */
      public Builder setExecutable(boolean value) {
        
        executable_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This account's data contains a loaded program.
       * </pre>
       *
       * <code>bool executable = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecutable() {
        
        executable_ = false;
        onChanged();
        return this;
      }

      private long rentEpoch_ ;
      /**
       * <pre>
       * The epoch at which this account will next owe rent.
       * </pre>
       *
       * <code>uint64 rent_epoch = 6;</code>
       * @return The rentEpoch.
       */
      @java.lang.Override
      public long getRentEpoch() {
        return rentEpoch_;
      }
      /**
       * <pre>
       * The epoch at which this account will next owe rent.
       * </pre>
       *
       * <code>uint64 rent_epoch = 6;</code>
       * @param value The rentEpoch to set.
       * @return This builder for chaining.
       */
      public Builder setRentEpoch(long value) {
        
        rentEpoch_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The epoch at which this account will next owe rent.
       * </pre>
       *
       * <code>uint64 rent_epoch = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRentEpoch() {
        
        rentEpoch_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The data held in this account.
       * </pre>
       *
       * <code>bytes data = 7;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * The data held in this account.
       * </pre>
       *
       * <code>bytes data = 7;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The data held in this account.
       * </pre>
       *
       * <code>bytes data = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private long writeVersion_ ;
      /**
       * <pre>
       * A global monotonically increasing atomic number, which can be used
       * to tell the order of the account update. For example, when an
       * account is updated in the same slot multiple times, the update
       * with higher write_version should supersede the one with lower
       * write_version.
       * </pre>
       *
       * <code>uint64 write_version = 8;</code>
       * @return The writeVersion.
       */
      @java.lang.Override
      public long getWriteVersion() {
        return writeVersion_;
      }
      /**
       * <pre>
       * A global monotonically increasing atomic number, which can be used
       * to tell the order of the account update. For example, when an
       * account is updated in the same slot multiple times, the update
       * with higher write_version should supersede the one with lower
       * write_version.
       * </pre>
       *
       * <code>uint64 write_version = 8;</code>
       * @param value The writeVersion to set.
       * @return This builder for chaining.
       */
      public Builder setWriteVersion(long value) {
        
        writeVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A global monotonically increasing atomic number, which can be used
       * to tell the order of the account update. For example, when an
       * account is updated in the same slot multiple times, the update
       * with higher write_version should supersede the one with lower
       * write_version.
       * </pre>
       *
       * <code>uint64 write_version = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearWriteVersion() {
        
        writeVersion_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:javaprotobuf.UpdateAccountEvent)
    }

    // @@protoc_insertion_point(class_scope:javaprotobuf.UpdateAccountEvent)
    private static final javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent();
    }

    public static javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateAccountEvent>
        PARSER = new com.google.protobuf.AbstractParser<UpdateAccountEvent>() {
      @java.lang.Override
      public UpdateAccountEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateAccountEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateAccountEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateAccountEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public javaprotobuf.UpdateAccountEventOuterClass.UpdateAccountEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_javaprotobuf_UpdateAccountEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_javaprotobuf_UpdateAccountEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030UpdateAccountEvent.proto\022\014javaprotobuf" +
      "\"\240\001\n\022UpdateAccountEvent\022\014\n\004slot\030\001 \001(\004\022\016\n" +
      "\006pubkey\030\002 \001(\014\022\020\n\010lamports\030\003 \001(\004\022\r\n\005owner" +
      "\030\004 \001(\014\022\022\n\nexecutable\030\005 \001(\010\022\022\n\nrent_epoch" +
      "\030\006 \001(\004\022\014\n\004data\030\007 \001(\014\022\025\n\rwrite_version\030\010 " +
      "\001(\004b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_javaprotobuf_UpdateAccountEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_javaprotobuf_UpdateAccountEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_javaprotobuf_UpdateAccountEvent_descriptor,
        new java.lang.String[] { "Slot", "Pubkey", "Lamports", "Owner", "Executable", "RentEpoch", "Data", "WriteVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
